### PR TITLE
Feature/disable post job button if info missing

### PR DESCRIPTION
**Pull request by clandau**
# Description
Disable company "post a job" button if the company hasn't filled in their profile and uploaded a logo. 

What does this PR do?
Adds a required fields array to the store, and uses a filter function in `AccountInteriorLayout` to determine if all fields are present. If not, it disables the post a job button, and adds instruction text underneath the disabled button.

**This is a work in progress!** I'm expecting a lot of feedback and to have to change a lot! I am new to the codebase and next/react/tailwind. Not sure that the store is the appropriate place for the required fields array, and if we could somehow make it so that it's not hard coded. 
Also what do we think of a hover tooltip with the help text on the disabled button?

# Related Tickets and Documents
https://github.com/drewclem/protege/issues/297

## What gif best describes this PR or how it makes you feel? (optional)
Confused math

### CODE REVIEW

**Comment by drewclem** [comment]
@clandau Is this good to merge?

**Comment by clandau** [comment]
@drewclem sure if you think so. you may want to confirm that the required field array has everything needed.

**Comment by drewclem** [comment]
@clandau Ok, I just saw it was marked as a draft and wasn't sure if you had more planned for it. Didn't want to preemptively merge

**Comment by drewclem** [comment]
This looks great @clandau !

I massaged the requiredCompanyFields a little bit- but other than that it works perfectly!

**Pull request merged**
