### PR TITLE
Issue#66

### PR DESCRIPTION
**Pull request by ottogutierrez**
Hi @drewclem, 

I'm submitting a PR that fixes issue#66.

Let me know if there are any questions.

Thanks!

### CODE REVIEW

**Comment by drewclem** [comment]
This isn't quite there. setEmail('') does clear out the data in the state, but it's doing so before the call to the mailing list api. It should be on line 26 after the fetch method.

It also isn't updating the value of the input element on the front-end, so the previously entered email is still staying there. You may have to add a ref to the input and then set its value to empty as well right after setEmail('').

It's close! It just needs a little bit more. Thank you for your time and effort on this.

**Comment by ottogutierrez** [comment]
Thanks for the input and apologize for missing those points. I think this should work now

**Comment by ottogutierrez** [comment]
Thanks for the input @drewclem and apologize for missing those points. I think this should work now

**Comment by ottogutierrez** [comment]
Hi there, do you have any updates or feedback on this pull request? Let me know if you have any questions, thanks!

**Comment by drewclem** [comment]
Hey Otto,

I apologize for being so slow getting back to this.

The issue I'm seeing right now is that I'm unable to type into the input field. So, it seems like clearing out the field is working - but it's firing on every keystroke keeping it from being usable.

What's an email I can reach you out and we can figure out a way to move forward.

**Comment by ottogutierrez** [comment]
Hi @drewclem! I’m sorry about this I’m a newbie still and missed that. My email is ottogutierrez@me.com, thanks for your message!

**Comment by ottogutierrez** [comment]
Hi @drewclem, as we discussed, I implemented my proposed changes to make this work as expected. Let me know if you have any questions

Thank you!

**Pull request merged**
